# docker-compose.yml
version: '3.8'

services:
  trading:
    build: .
    container_name: trading_simulation
    volumes:
      - output:/app/output
    environment:
      POOL_SIZE: "250"
      SIMULATION_DURATION: "10"
      NUM_PRODUCTS: "15"
    command: ["/app/.venv/bin/python main.py | tee /app/output/trading-$(date +'%Y%m%d_%H%M%S').log"]

volumes:
  output:
    driver: local
    driver_opts:
      type: none
      device: ./output
      o: bind
