# docker-compose.yml
version: '3.8'

services:
  trading:
    build:
      context: .
      args:
        POOL_SIZE: ${POOL_SIZE:-200}
        SIMULATION_DURATION: ${SIMULATION_DURATION:-120}
        NUM_PRODUCTS: ${NUM_PRODUCTS:-10}
    container_name: trading_simulation
    volumes:
      - output:/app/output
    environment:
      POOL_SIZE: ${POOL_SIZE:-200}
      SIMULATION_DURATION: ${SIMULATION_DURATION:-120}
      NUM_PRODUCTS: ${NUM_PRODUCTS:-10}
    command: ["/app/.venv/bin/python main.py | tee /app/output/trading-$(date +'%Y%m%d_%H%M%S').log"]

volumes:
  output:
    driver: local
    driver_opts:
      type: none
      device: ./output
      o: bind
